apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-xjd6
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-xjd6
    app.kubernetes.io/part-of: tkrw-pr712-0075-0015-app
  name: devfile-sample-xjd6
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-xjd6
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-xjd6
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0015-tenant/tkrw-pr712-0075-0015-app/devfile-sample-xjd6@sha256:dc5ac751301d80e4ef23ac3119fd2114a503dcb280cccb2975cf5a47d2ee52f9
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
